// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBO4HeKssuVW8hfCFfo0v35OZv0DfCak3g',
    appId: '1:112284466516:web:678a39c062d98fa9d3dcc1',
    messagingSenderId: '112284466516',
    projectId: 'knowledge-efacb',
    authDomain: 'knowledge-efacb.firebaseapp.com',
    storageBucket: 'knowledge-efacb.appspot.com',
    measurementId: 'G-C20LVW76Y0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5xluxpkdEO5t9bGjNhDebbaknUKc9SQQ',
    appId: '1:112284466516:android:650a5f8950f6770bd3dcc1',
    messagingSenderId: '112284466516',
    projectId: 'knowledge-efacb',
    storageBucket: 'knowledge-efacb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAooeOwTabD3BkftxcbsiQibe38m07sO_g',
    appId: '1:112284466516:ios:513ac58fd8448265d3dcc1',
    messagingSenderId: '112284466516',
    projectId: 'knowledge-efacb',
    storageBucket: 'knowledge-efacb.appspot.com',
    iosBundleId: 'com.example.assignmentcw',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAooeOwTabD3BkftxcbsiQibe38m07sO_g',
    appId: '1:112284466516:ios:bb7534649b80be76d3dcc1',
    messagingSenderId: '112284466516',
    projectId: 'knowledge-efacb',
    storageBucket: 'knowledge-efacb.appspot.com',
    iosBundleId: 'com.example.assignmentcw.RunnerTests',
  );
}
